<nav class = "menu">
    <div class = "row" style="background-color:black">
        <div class = "col-1 offset-5">
            <h1 style="color:white" class="logo">Barbearia</h1>
        </div>
    </div>
    <div class = "row card" >   
        <div class = "col-4 offset-5" style="heigth:100px">
            <a href = "index.php"> Fazer agendamento </a> &nbsp &nbsp
            <a href = "lista_agendamento.php"> Lista de agendamento </a>
        </div>
    </div>
</nav>